name: Deploy myapp1 to AWS Server

# Trigger this workflow on pushes to the main branch
on:
  push:
    branches:
      - main  # Change if you are using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Navigating to the application directory"
            cd /home/ubuntu/App/Arman/myapp1

            echo "Pulling latest changes from GitHub"
            git pull origin main

            # Optional: Add any additional commands needed for your deployment
            # For example, if you need to run migrations for a Django app:
            # python manage.py migrate
            # or restart a service:
            # sudo systemctl restart gunicorn
